name: build
on:
  push:
    branches:
      - CI_BDD
  pull_request:
    branches:
      - CI_BDD

jobs:
  build:
    runs-on: ubuntu-latest
    # use a known build environment
    container: python:3.9

    # Required services    
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: TDD
        run: nosetests
        env:
          DATABASE_URI: "postgres://postgres:postgres@postgres:5432/testdb"

      - name: BDD
        run: |
          apt-get install -y python3-selenium chromium-chromedriver
          LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
          curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
          unzip chromedriver_linux64.zip -d ~/bin
          chromedriver --version
          curl -X GET http://localhost:5984/
          curl -X PUT http://admin:pass@localhost:5984/test
          gunicorn --log-level=critical --bind=127.0.0.1:8080 service:app &
          sleep 5
          curl -I http://localhost:8080/
          behave

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
