name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # use a known build environment
    container: python:3.9

    # Required services    
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: TDD
        run: nosetests
        env:
          DATABASE_URI: "postgres://postgres:postgres@postgres:5432/testdb"

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: 744fd982-1d0c-4176-bc86-cdea98fc4f45
